### PR TITLE
Add xbps support

### PR DESCRIPTION
**Pull request by juuyokka**
Add xbps support after discussion in #7 
image

### CODE REVIEW

**Comment by Notarin** [comment]
If you are fine with my changes I am ready to approve

**Comment by Notarin** [comment]
Small change of plans, I'm putting this on a teeny tiny pause, I have some changes I want to implement that I'd like to have before I merge this, if I have the opportunity to tonight I will do so, if not I will merge it anyways.

**Comment by juuyokka** [comment]
> If you are fine with my changes I am ready to approve

lgtm, you can merge whenever you feel appropriate

**Comment by Notarin** [comment]
fyi, I force pushed to get your fork up to date

**Comment by Notarin** [comment]
congrats, you've authored version 0.2.0, thank you for your contribution!

**Pull request merged**
